version: '3.8'

services:
  web-production:
    image: ghcr.io/adminvpshub/do-cu-trung-kien:latest
    ports:
      - "3007:3007"
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
